### ISSUE TITLE
更新缓存的Bug

### ISSUE THREAD

**Issue by WDevaloper** [lihangleo2/smartVpageAdapterlibrary#1]
如果limit设置为2或3，往通过add(0,datas)不回走Fragment生命周期，那么如何更新已经缓存的数据呢？比如：当前滑动到2，这时候想要往前放置数据，那么0和1位置的数据怎么更新，似乎这个框架存在的问题哦

**Comment by lihangleo2** [comment]
首先不管你ilimit设置多少，新添加数据的fragment是一定会走生命周期的，也就是已经生成的fragment如何刷新数据问题。首先，我们要确保list数据源里的bean对象还是那个bean，比如是否收藏，当bean里的isCollect发生改变的时候，我们完全可以在，fragment里的onHiddenChanged方法，去更新ui，也就是页面再次可见的时候，我们可以更新我们bean对象里某个字段的更新。

**Comment by WDevaloper** [comment]
1、我i测试了，新添加的不走生命周期哦，只有limit中的才走生命周期哦。

**Comment by lihangleo2** [comment]
新增的怎么可能不走生命周期，比如你现在有5个，不管是往前增加还是往后增加，因为是无感添加，他肯定是不回立即走，一定会等你滑动它的位置，它才会被创建，才会走的啊。
